<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CareDocumentController;
use App\Http\Controllers\CareEntryController;
use App\Http\Controllers\CareGroupController;
use App\Http\Controllers\CareOverviewController;
use App\Http\Controllers\CareRecipientController;
use App\Http\Controllers\OrganizationInvitationController;
use App\Http\Controllers\OrganizationMemberController;
use App\Http\Controllers\OrganizationRoleController;
use App\Http\Controllers\PasswordRecoveryController;
use App\Http\Controllers\RecipientAvatarController;
use App\Http\Middleware\VerifyPasswordToken;
use Illuminate\Support\Facades\Route;

Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:auth-login');
Route::post('auth/register', [AuthController::class, 'register'])->middleware('throttle:auth-register');
Route::post('auth/forgot-password', [PasswordRecoveryController::class, 'store'])->middleware('throttle:auth-recovery');
Route::post('auth/reset-password', [PasswordRecoveryController::class, 'update'])->middleware('throttle:auth-recovery');
Route::get('organization-invitations/accept/{token}', [OrganizationInvitationController::class, 'showAcceptance']);
Route::post('organization-invitations/accept/{token}', [OrganizationInvitationController::class, 'accept'])->middleware('throttle:auth-register');
Route::middleware(['auth:api', VerifyPasswordToken::class])->group(function () {
    Route::get('groups', [CareGroupController::class, 'index']);
    Route::post('groups', [CareGroupController::class, 'store']);
    Route::get('auth/me', [AuthController::class, 'me']);
    Route::post('auth/logout', [AuthController::class, 'logout']);
    Route::post('auth/refresh', [AuthController::class, 'refresh']);
});
Route::middleware(['auth:api', VerifyPasswordToken::class, 'tenant'])->group(function () {
    Route::get('auth/context', [AuthController::class, 'context']);
    Route::get('my-recipient-avatar', [RecipientAvatarController::class, 'show']);
    Route::post('my-recipient-avatar', [RecipientAvatarController::class, 'store']);
    Route::delete('my-recipient-avatar', [RecipientAvatarController::class, 'destroy']);
    Route::get('organization-members', [OrganizationMemberController::class, 'index'])->middleware('can:organization-members.view');
    Route::patch('organization-members/{user}/role', [OrganizationMemberController::class, 'updateRole'])->middleware('can:organization-members.update-role');
    Route::patch('organization-members/{user}/status', [OrganizationMemberController::class, 'updateStatus'])->middleware('can:organization-members.update-status');
    Route::get('organization-roles', [OrganizationRoleController::class, 'index']);
    Route::get('organization-invitations', [OrganizationInvitationController::class, 'index'])->middleware('can:organization-members.invite');
    Route::post('organization-invitations', [OrganizationInvitationController::class, 'store'])->middleware('can:organization-members.invite');
    Route::post('organization-invitations/{invitation}/resend', [OrganizationInvitationController::class, 'resend'])->middleware('can:organization-members.invite');
    Route::patch('organization-invitations/{invitation}/revoke', [OrganizationInvitationController::class, 'revoke'])->middleware('can:organization-members.invite');
    Route::apiResource('recipients', CareRecipientController::class);
    Route::get('recipients/{recipient}/accesses', [CareRecipientController::class, 'accesses']);
    Route::put('recipients/{recipient}/accesses', [CareRecipientController::class, 'grant']);
    Route::delete('recipients/{recipient}/accesses/{user}', [CareRecipientController::class, 'revoke']);
    Route::post('recipients/{recipient}/entries/{entry}/execution', [CareEntryController::class, 'execute']);
    Route::post('recipients/{recipient}/entries/{entry}/proposals/{proposal}/decision', [CareEntryController::class, 'decide']);
    Route::post('recipients/{recipient}/entries/{entry}/proposals/{proposal}/withdraw', [CareEntryController::class, 'withdraw']);
    Route::get('recipients/{recipient}/entries', [CareEntryController::class, 'index']);
    Route::post('recipients/{recipient}/entries', [CareEntryController::class, 'store']);
    Route::put('recipients/{recipient}/entries/{entry}', [CareEntryController::class, 'update']);
    Route::patch('recipients/{recipient}/entries/{entry}/complete', [CareEntryController::class, 'complete']);
    Route::delete('recipients/{recipient}/entries/{entry}', [CareEntryController::class, 'destroy']);
    Route::post('recipients/{recipient}/entries/{entry}/shares/{share}/pay', [CareEntryController::class, 'pay']);
    Route::get('recipients/{recipient}/documents', [CareDocumentController::class, 'index']);
    Route::post('recipients/{recipient}/documents', [CareDocumentController::class, 'store']);
    Route::get('recipients/{recipient}/documents/{document}/download', [CareDocumentController::class, 'download']);
    Route::delete('recipients/{recipient}/documents/{document}', [CareDocumentController::class, 'destroy']);
    Route::get('agenda', [CareOverviewController::class, 'agenda']);
    Route::get('notifications', [CareOverviewController::class, 'notifications']);
    Route::post('notifications/{notification}/read', [CareOverviewController::class, 'read']);
});
